name: lifeos
description: A comprehensive team and personal productivity collaboration app with integrated AI assistant.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #agora
  agora_rtc_engine: ^6.5.2
  permission_handler: ^12.0.1
  upgrader: ^11.5.0 
  http: ^1.2.1
  agora_rtm: ^2.2.5
  # State Management
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.1.0

  # Navigation
  go_router: ^10.0.0

  # Network
  dio: ^5.0.0
  web_socket_channel: ^2.3.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Database - Supabase & PowerSync
  supabase_flutter: ^2.6.0  # Updated for newer SDK compatibility
  powersync: ^1.9.0  # Updated PowerSync SDK for real-time sync
  path_provider: ^2.1.3
  path: ^1.9.0

  # Authentication
  local_auth: ^2.3.0
  js: ^0.7.1

  # UI Components (will add platform-specific ones later)
  # flutter_adaptive_scaffold: ^0.1.7+1
  # fluent_ui: ^4.8.6
  # macos_ui: ^2.0.2

  # Utilities
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  uuid: ^4.0.0  # Updated for PowerSync compatibility
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0  # Updated to latest version compatible with Flutter 3.35.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.0
  json_serializable: ^6.6.0
  riverpod_generator: ^2.2.0

  # Testing (using compatible version)
  mockito: ^5.3.0
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  # Fix win32 package compatibility issue on macOS
  win32: ^5.5.0
  # Fix sqlite_async compatibility with newer sqlite3
  sqlite_async: ^0.12.0
  sqlite3: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
